### PR TITLE
fix: Fix CLI download to work with older versions of data stored in Firebase

### LINKED ISSUE #299: Don't overwrite 'results` field when trials subcollection doesn't exist
`trials` sub collection is only used on newer tasks. For old tasks all the data is found in `experimentData` - the backwards compatibility will be easy

### PR DESCRIPTION
**Pull request by RobertGemmaJr**
Older versions of Honeycomb didn't store experiment data in the nested "trials" subcollection. The CLI was overriding those results with an empty array. We now skip that step if the Firebase document doesn't have that subcollection

### CODE REVIEW

**Comment by RobertGemmaJr** [comment]
Note to self - I need to update the CLI discussion post with this code once it's merged

File: cli.mjs [hunk 1]
```diff
@@ -65,20 +65,25 @@ async function downloadDataFirebase() {
...
+    const trialsSnapshot = await experimentRef.collection(TRIALS_COL).orderBy("trial_index").get();
+    if (!trialsSnapshot.empty) {
+      // Add the trials' data to the experiment's data as "results" array
+      const trialsData = trialsSnapshot.docs.map((trial) => trial.data());
+      experimentData["results"] = trialsData;
+    } else {
+      // Running in an older version of Honeycomb where "trials" subcollection doesn't exist
+      // All experiment data used to be stored inside the experiment document -
+      // In this case "results" is already inside the experimentData object
+    }
```
Comment (digicosmos86) [inline cli.mjs:78]: Why an empty else clause here? Are you just using it for the comment?

**Review by digicosmos86 — APPROVED** [review]
Looks great to me!

File: cli.mjs (hunk 1 above)
Comment (RobertGemmaJr) [reply cli.mjs:78]: Yeah, I wanted to make sure I noted that there is an "else" for backwards compatibility, it just doesn't have to do anything
